config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  resources :carts
  resources :products do
    member do
      resource :cart, only: [:update] do
        [:add, :remove, :change_amount].each do |action|
          patch action, to: "carts#update", as: "#{action}_product_in", defaults: { update_action: action.to_s }
        end
      end
    end
  end
  
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :product_orders, dependent: :destroy
  has_many :products, through: :product_orders

  validates :first_name, :last_name, :address, :phone, presence: true

  scope :ordered, -> { order(last_name: :asc) }

  def product_sum(product)
    ProductOrder.joins(:product).where(order_id: id, product_id: product.id).sum('product_orders.amount * products.price')
  end

  def product_amount(product)
    product_orders.find_by(product:).amount
  end

  def total_sum
    ProductOrder.joins(:product).where(order_id: id).sum('product_orders.amount * products.price')
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_orders, dependent: :destroy
  has_many :orders, through: :product_orders

  validates :title, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :balance, numericality:  { greater_than_or_equal_to: 0 }

  scope :ordered, -> { order(title: :asc) }
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :amount, numericality: { greater_than_or_equal_to: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :init_cart, only: :update

  def index
    @cart = Cart::Manager.new(session, cart_params)
  end

  def update
    notice = Cart::Manager.new(session, params).call

    redirect_back fallback_location: root_path, notice: notice
  end

  def destroy
    session.delete(:products)

    redirect_to products_path, notice: "Cart was cleaned"
  end

  private

  def init_cart
    session[:products] = {} if session[:products].blank?
  end

  def cart_params
    params.permit(:id, :amount, :update_action)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :init_cart, only: :update

  def index
    @cart = Cart::Manager.new(session, cart_params)
  end

  def update
    notice = Cart::Manager.new(session, params).call

    redirect_back fallback_location: root_path, notice: notice
  end

  def destroy
    session.delete(:products)

    redirect_to products_path, notice: "Cart was cleaned"
  end

  private

  def init_cart
    session[:products] = {} if session[:products].blank?
  end

  def cart_params
    params.permit(:id, :amount, :update_action)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :check_cart, only: [:new, :create]

  def show
    @order = resourse
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      Orders::Manager.new(session[:products], @order, session).call
      
      redirect_to order_path(@order), notice: "Order was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    resourse.destroy

    redirect_to products_path, notice: "Order successfully destroyed."
  end

  private

  def collection
    Order.ordered
  end

  def resourse
    collection.find(params[:id])
  end
  
  def order_params
    params.require(:order).permit(:first_name, :last_name, :address, :phone)
  end

  def check_cart
    redirect_to products_path, notice: "Your cart is empty yet" if session[:products].blank?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = collection
  end

  def show
    @product = resource
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    
    if @product.save
      redirect_to products_path(@product), notice: 'Product was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = resource
  end

  def update
    @product = resource

    if @product.update(product_params)
      redirect_to products_path(@product), notice: 'Product was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = resource

    @product.destroy

    redirect_to products_path, notice: 'Product was successfully destroyed.'
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :balance)
  end

  def collection
    Product.ordered
  end

  def resource
    collection.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cart/index.html.erb
<div class="flex flex-col">
  <div class="overflow-x-auto">
    <div class="inline-block min-w-full py-2 ">
      <div class="overflow-hidden">
        <% if session[:products].present? %>
          <table class="min-w-full mx-4 text-sm font-light text-left ">
            <thead class="font-medium border-b dark:border-neutral-500">
              <tr>
                <th scope="col" class="px-6 py-4">Name</th>
                <th scope="col" class="px-6 py-4">Price</th>
                <th scope="col" class="px-6 py-4">Amount</th>
                <th scope="col" class="px-6 py-4">Sum</th>
                <th scope="col" class="px-6 py-4">Delete</th>
              </tr>
            </thead>
            <tbody>
              <% @cart.items.each do |product| %>
                <tr class="border-b hover:bg-neutral-100 dark:border-neutral-300">
                  <td class="px-6 py-4 whitespace-nowrap"><%= product.title %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= number_to_currency(product.price, :unit => "₴") %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= render "cart/change_amount_form", product: product %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= number_to_currency(@cart.product_sum(product), unit: "₴") %></td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <%= button_to remove_product_in_cart_path(product), method: :patch do %>
                        <i class="fa fa-regular fa-trash fa-2x"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              <tr class="border-b dark:border-neutral-300">
                <td colspan="3" class="px-6 py-2 font-bold whitespace-nowrap">
                  Total sum
                </td>
                <td class="px-6 py-2 font-bold whitespace-nowrap"><%= number_to_currency(@cart.sum, :unit => "₴") %></td>
              </tr>
            </tbody>
          </table>

          <div class="flex items-center justify-between">
            <div class="inline-block m-5">
                <%= link_to 'Pay this order', new_order_path, class: "btn-pay" %>
            </div>
            
            <div class="inline-block m-5">
              <%= button_to 'Delete all products', cart_path(@cart), method: :delete, class: "text-white bg-gray-500 font-medium rounded-lg px-5 py-2.5 text-sm" %>
            </div>
          </div>
        <% else %>
            <div class="grid h-screen text-3xl place-items-center">Your cart is empty</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/carts/_buy_form.html.erb
<%= form_with url: add_product_in_cart_path(product), method: :patch do |f| %>
  <%= f.number_field :amount, min: 1, value: session.dig(:products, product.id.to_s) || 0, class:'rounded-lg input-field w-24 h-9 inline-block' %>
  <%= f.submit "Add to cart", class: "btn-blue" %>
<% end %>

app/views/carts/_change_amount_form.html.erb
<%= form_with url: change_amount_product_in_cart_path(product), method: :patch do |f| %>
  <%= f.number_field :amount, min: 1, value: session.dig(:products, product.id.to_s), class:'rounded-lg input-field w-24 h-9 inline-block' %>
  <%= f.submit "Change amount", class: "btn-blue" %>
<% end %>

app/views/carts/index.html.erb
<div class="flex flex-col">
  <div class="overflow-x-auto">
    <div class="inline-block min-w-full py-2 ">
      <div class="overflow-hidden">
        <% if session[:products].present? %>
          <table class="min-w-full mx-4 text-sm font-light text-left ">
            <thead class="font-medium border-b dark:border-neutral-500">
              <tr>
                <th scope="col" class="px-6 py-4">Name</th>
                <th scope="col" class="px-6 py-4">Price</th>
                <th scope="col" class="px-6 py-4">Amount</th>
                <th scope="col" class="px-6 py-4">Sum</th>
                <th scope="col" class="px-6 py-4">Delete</th>
              </tr>
            </thead>
            <tbody>
              <% @cart.items.each do |product| %>
                <tr class="border-b hover:bg-neutral-100 dark:border-neutral-300">
                  <td class="px-6 py-4 whitespace-nowrap"><%= product.title %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= number_to_currency(product.price, :unit => "₴") %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= render "carts/change_amount_form", product: product %></td>
                  <td class="px-6 py-4 whitespace-nowrap"><%= number_to_currency(@cart.product_sum(product), unit: "₴") %></td>
                  <td class="px-6 py-4 whitespace-nowrap">
                    <%= button_to remove_product_in_cart_path(product), method: :patch do %>
                        <i class="fa fa-regular fa-trash fa-2x"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              <tr class="border-b dark:border-neutral-300">
                <td colspan="3" class="px-6 py-2 font-bold whitespace-nowrap">
                  Total sum
                </td>
                <td class="px-6 py-2 font-bold whitespace-nowrap"><%= number_to_currency(@cart.sum, :unit => "₴") %></td>
              </tr>
            </tbody>
          </table>

          <div class="flex items-center justify-between">
            <div class="inline-block m-5">
                <%= link_to 'Pay this order', new_order_path, class: "btn-pay" %>
            </div>
            
            <div class="inline-block m-5">
              <%= button_to 'Delete all products', cart_path(@cart), method: :delete, class: "text-white bg-gray-500 font-medium rounded-lg px-5 py-2.5 text-sm" %>
            </div>
          </div>
        <% else %>
            <div class="grid h-screen text-3xl place-items-center">Your cart is empty</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_alert.html.erb
<% if alert.present? %>
  <p class="inline-block px-3 py-3 mb-5 font-medium text-center text-red-500 rounded-lg bg-white-50" id="alert"><%= alert %></p>
<% end %>

app/views/layouts/_header.html.erb
<nav class="relative flex flex-wrap items-center justify-between w-full py-2 shadow-lg bg-neutral-100 text-neutral-200 dark:bg-neutral-600">
  <div class="flex flex-wrap items-center justify-between w-full px-3">
    <div class="flex items-center justify-between" id="links">
      <%= link_to 'Products', products_path, class: "nav-item" %>
    </div>

    <%= link_to carts_path  do %>
      <i class="fa fa-solid fa-cart-shopping fa-2x nav-item me-5"></i>
    <% end %>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% flash.each do |type, message| %>
  <p id="<%= type %>"><%= message %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoreProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <script src="https://kit.fontawesome.com/c34a6ab486.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/notice' %>

    <main class="container flex px-5 mx-auto mt-28">
      <%= yield %>
    </main>
  </body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for order, url: orders_path, method: :post do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :address %>
  <%= f.input :phone %>

  <%= f.button :submit, "Create order", class: 'btn-blue' %>
<% end %>

app/views/orders/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">Editing order</h1>

  <%= render "orders/form", order: @order %>

  <%= link_to "Show this order", @order, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to orders", orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/orders/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">New order</h1>

  <%= render "orders/form", order: @order %>

  <%= link_to 'Back to cart', carts_path, class: "btn-grey" %>
</div>

app/views/orders/show.html.erb
<div class="flex w-full mx-auto">
  <div class="mx-auto">
    <div class="flex flex-col overflow-x-auto text-base text-neutral-600 dark:text-neutral-900 sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 overflow-hidden sm:px-6 lg:px-8 ">
        <div class="block p-6 bg-white border-2 rounded-lg ">
          <ul class="ms-6 w-96">
            <h1 class="my-5 text-3xl font-bold">Order №<%= @order.id %></h1>
            <li class="mb-3"><%= @order.first_name %></li><hr>
            <li class="mb-3"><%= @order.last_name %></li><hr>
            <li class="mb-3"><%= @order.address %></li><hr>
            <li class="mb-3"><%= @order.phone %></li><hr>
          </ul>
          <table class="min-w-full p-3 my-6 text-sm font-light text-left border-2">
            <thead class="font-medium border-b dark:border-neutral-500">
              <tr>
                <th scope="col" class="table-item">Title</th>
                <th scope="col" class="table-item">Price</th>
                <th scope="col" class="table-item">Amount</th>
                <th scope="col" class="table-item">Sum</th>
              </tr>
            </thead>
            <tbody>
              <% @order.products.each do |product| %>
                <tr class="border-b dark:border-neutral-500">
                  <td class="table-item"><%= product.title %></td>
                  <td class="table-item"><%= number_to_currency(product.price, :unit => "₴") %></td>
                  <td class="text-center table-item"><%= @order.product_amount(product) %></td>
                  <td class="table-item"><%= number_to_currency(@order.product_sum(product), :unit => "₴") %></td>
                </tr>
              <% end %>
              <tr class="border-b dark:border-neutral-500">
                <td colspan="3" class="px-6 py-2 font-bold ">
                  Total sum
                </td>
                <td class="px-6 py-2 font-bold ">
                  <%= number_to_currency(@order.total_sum, :unit => "₴") %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="inline-block ml-2">
      <%= button_to 'Destroy this order', order_path(@order), method: :delete, class: "btn-grey" %>
    </div>
    <div class="inline-block ml-2">
      <%= link_to 'Back to products', products_path, class: "btn-grey" %>
    </div>
  </div>
</div>

app/views/products/_form.html.erb
<%= simple_form_for product, url: products_path, method: :post do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :balance %>

  <%= f.button :submit, "Create product", class: "btn-blue" %>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p class="my-5">
    <strong class="block mb-1 font-medium">Title:</strong>
    <%= product.title %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Description:</strong>
    <%= product.description %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Price:</strong>
    <%= number_to_currency(product.price) %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Balance:</strong>
    <%= product.balance %>
  </p>

  <%= link_to "Show this product", product, class: "btn-grey" %>
  <%= link_to 'Edit this product', edit_product_path(product), class: "btn-grey" %>
  <div class="my-5">
    <%= render "carts/buy_form", product: product %>
  </div>
  <hr class="mt-6">
</div>

app/views/products/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">Editing product</h1>

  <%= render "products/form", product: @product %>

  <%= link_to "Show this product", @product, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/index.html.erb
<div class="w-full">
  <div class="flex items-center justify-between pb-8">
    <h1 class="mx-auto text-lg text-4xl font-bold">Products</h1>
  </div>
  <table id="products" class="mx-auto">
    <tfoot>
      <tr>
        <td colspan="3">
          <div class="mt-8">
            <%= link_to 'New product', new_product_path, class: "inline rounded-lg py-3 px-5 bg-green-600 text-white block font-medium" %>
          </div>
        </td>
      </tr>
  </tfoot>
  <tbody> 
    <%= render @products%>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">New product</h1>

  <%= render "products/form", product: @product %>

  <%= link_to 'Back to products', products_path, class: "btn-back" %>
</div>

app/views/products/show.html.erb
<div class="mx-auto">
  <div class="w-full p-1 m-5 md:p-2">
    <div class="grid grid-cols-1 gap-4">
      <div class="text-3xl font-semibold text-center">
        <%= @product.title %>
      </div>

      <div>
        <%= @product.description %>
      </div>

      <div>
        Price: <%= number_to_currency(@product.price, unit: "₴ ") %>
      </div>

      <div>
        Available: <%= @product.balance %>
      </div>
    </div>

    <div class="relative mb-3">
      <% if @product.balance.nonzero? %>
        <%= render "carts/buy_form", product: @product %>
      <% end %>
    </div>

    <div class="inline-block">
       <%= link_to 'Edit this product', edit_product_path(@product), class: "btn-grey" %>
      <div class="inline-block ml-2">
        <%= button_to 'Destroy this product', product_path(@product), method: :delete, class: "btn-grey" %>
      </div>
      <%= link_to 'Back to products', products_path, class: "btn-grey" %>
    </div>
  </div>
</div>